language: node_js
branches:
  only:
    - master
    - "/^greenkeeper/.*$/"
cache:
  directories:
    - "~/.npm"
notifications:
  email: false
install:
  - npm i -g firebase-tools
  - npm install
script:
  - npm run test
  - npm run build
before_deploy:
  - npm install --prefix ./functions
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - npm install semantic-release @semantic-release/git @semantic-release/changelog --no-save
  - npm run travis-deploy-once "npm run semantic-release"
