language: node_js
branches:
  only:
    - master
    - "/^greenkeeper/.*$/"
cache:
  directories:
    - "~/.npm"
notifications:
  email: false
before_install:
  - npm i -g firebase-tools
install:
  - npm install
  - npm install semantic-release @semantic-release/git @semantic-release/changelog --no-save
script:
  - npm run test
  - npm run build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm install --prefix ./functions
  - firebase deploy --only functions --token "${FIREBASE_TOKEN}"
